name: Podman Quay Cache
description: Cache podman images in Quay
author: https://github.com/KennaSecurity
requirements:
  - KennaSecurity/podman
  - coyainsurance/s3-cache
configuration:
  properties:
    build-args:
      type: [array, string]
    additional-build-args:
      type: string
    cache-on:
      type: [array, string]
    dockerfile:
      type: string
    repo-name:
      type: string
    target:
      type: string
  required: []
